# Generated by Django 5.1.3 on 2025-03-31 15:08

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutumnSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='')),
                ('session_date', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Shanbe'), ('1', 'YekShanbe'), ('2', 'DoShanbe'), ('3', 'SeShanbe'), ('4', 'CharShanbe'), ('5', 'PanjShanbe'), ('6', 'Jomae')], max_length=13, verbose_name='روز های برگذاری')),
                ('session_time', models.TimeField()),
                ('enrollment_capacity', models.IntegerField(verbose_name='ظرفیت ثبت نام')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_name', to='courses.learningcourses')),
                ('group', models.ManyToManyField(related_name='amir', to='courses.learningcourses')),
            ],
        ),
        migrations.CreateModel(
            name='WinterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='')),
                ('session_date', multiselectfield.db.fields.MultiSelectField(choices=[('0', 'Shanbe'), ('1', 'YekShanbe'), ('2', 'DoShanbe'), ('3', 'SeShanbe'), ('4', 'CharShanbe'), ('5', 'PanjShanbe'), ('6', 'Jomae')], max_length=13, verbose_name='روز های برگذاری')),
                ('session_time', models.TimeField()),
                ('enrollment_capacity', models.IntegerField(verbose_name='ظرفیت ثبت نام')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.learningcourses')),
                ('group', models.ManyToManyField(related_name='catagory', to='courses.learningcourses')),
            ],
        ),
    ]
